<?php
/**
 * Created by PhpStorm.
 * User: asus
 * Date: 2019/10/11
 * Time: 11:49
 */

namespace app\admin\controller;


use think\Db;

class Cate extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function openinsert(){
        $cate=Db::table('category')->order('cid','asc')->select();
        $this->assign('cates',$cate);//挂载变量
        return $this->fetch();
    }
    public function insert(){
        $data=input('post.');
        $result=Db::table('category')->insert($data);
        if($result>0) {
            return json([
                'code'=>200,
                'msg'=>'插入成功'
            ]);
        }else{
            return json([
                'code'=>404,
                'msg'=>'插入失败'
            ]);
        }
    }
    public function query(){
        $count=Db::table('category')->count();

        $data=Db::table('category')->select();

        return json([
            'code'=>0,
            'msg'=>'数据获取成功',
            'data'=>$data,
            'count'=>$count
        ]);


    }
public function index(){
    $cate=Db::table('category')->select();
    $this->assign('cate',$cate);
        return $this->fetch();
}

    public function delete(){
        $qs=input('post.');
        $id=$qs['id'];
        $result=Db::table('category')->where('cid',$id)->delete();
        if($result>0){
            return json([
                'code'=>200,
                'msg'=>'删除成功'
            ]);
        }
    }
}
